[package]
name = "m3u8_parser"
version = "0.1.0"
authors = ["Zak"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0"
indexmap = "1.6"
